# Generated by Django 3.1.5 on 2021-01-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='code',
            field=models.CharField(default="HU-<method 'timestamp' of 'datetime.datetime' objects>", max_length=250),
        ),
    ]
