# Generated by Django 3.1.5 on 2021-01-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_visit_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='code',
            field=models.CharField(default='HU-<built-in function time>', max_length=250),
        ),
    ]
