# Generated by Django 3.1.5 on 2021-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20210118_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='code',
            field=models.CharField(default=1610956505.0937164, max_length=250),
        ),
    ]
