# Generated by Django 3.1.5 on 2021-01-18 08:23

from django.db import migrations, models
import visit.models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_auto_20210118_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='code',
            field=models.CharField(default=visit.models.Visit.get_visit_code, max_length=250),
        ),
    ]
