# Generated by Django 3.1.5 on 2021-01-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbluser',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
