# Generated by Django 3.1.5 on 2021-01-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210118_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbluser',
            name='country',
            field=models.CharField(choices=[('eg', 'EGYPT'), ('usa', 'USA')], default='EGYPT', max_length=100),
            preserve_default=False,
        ),
    ]
