# Generated by Django 3.1.5 on 2021-01-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_auto_20210118_0823'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='visit',
            field=models.ManyToManyField(to='visit.Visit'),
        ),
    ]
